name: Build JAR and Create Draft PR

on:
  push:
    tags:
      - 'v*'  # This will trigger the action when tags starting with 'v' (e.g., v1.0.0) are pushed.

jobs:
  build-and-pr:
    runs-on: ubuntu-24.04 

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y install nano

      - name: Build JAR and Push new Branch
        working-directory: docker/server
        run: |
          ./create-jar.sh
          # copy jar to artifacts folder
          mkdir -p artifacts/

          # remove old jar
          rm artifacts/hello-world*

          # copy latest jar
          mv hello-world.jar artifacts/hello-world-${{ github.ref_name }}.jar
      
      - name: Create draft PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}-IoT-Server-JAR
          title: "Include JAR for Release ${{ github.ref_name }}"
          body: |
            This PR includes the built IoT Server JAR file from release `${{ github.ref_name }}`.
          commit-message: Update IoT Server JAR from ${{ github.ref_name }}
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          add-paths: |
            docker/server/artifacts/*
          base: master
          draft: true
