name: build-jar

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-pr:
    runs-on: ubuntu-24.04 

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -y install nano

      - name: Build
        working-directory: docker/server
        run: |
          # Build JAR
          ./create-jar.sh

          # remove old jar
          rm jar/hello-world* || echo "Jar folder not Found, continuing..."

          # update latest jar
          mv hello-world.jar jar/hello-world-${{ github.ref_name }}.jar

      - name: Run
        working-directory: docker/server/jar
        run: |
          sleep 10

      - name: Create Draft Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}-IoT-Server-JAR
          title: "Update IoT Server JAR from Release ${{ github.ref_name }}"
          body: |
            This PR includes the built IoT Server JAR file from release `${{ github.ref_name }}`.
          commit-message: Update IoT Server JAR from ${{ github.ref_name }}
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          add-paths: |
            docker/server/jar/*
          base: master
          draft: true
